<?php

namespace Database\Seeders;

use App\Models\Hospital;
use Illuminate\Database\Seeder;

class HospitalSeeder extends Seeder
{
    public function run(): void
    {
        $hospitales = [
            [
                'nombre' => 'Hospital General de México',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Dr. Balmis 148, Doctores, Cuauhtémoc, CDMX',
                'telefono' => '55 5578 2200',
                'latitud' => 19.4168,
                'longitud' => -99.1528,
                'servicios' => 'Urgencias, UCI, Cirugía, Cardiología, Neurología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Juárez de México',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Av. IPN 5160, Magdalena de las Salinas, GAM, CDMX',
                'telefono' => '55 5748 1264',
                'latitud' => 19.4839,
                'longitud' => -99.1355,
                'servicios' => 'Urgencias, UCI, Cirugía, Oncología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Español',
                'tipo' => 'privado',
                'nivel' => 'tercero',
                'direccion' => 'Av. Ejército Nacional 613, Granada, Miguel Hidalgo, CDMX',
                'telefono' => '55 5253 3900',
                'latitud' => 19.4376,
                'longitud' => -99.1985,
                'servicios' => 'Urgencias, UCI, Cirugía, Cardiología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Ángeles del Pedregal',
                'tipo' => 'privado',
                'nivel' => 'tercero',
                'direccion' => 'Camino a Santa Teresa 1055, Héroes de Padierna, CDMX',
                'telefono' => '55 5445 1000',
                'latitud' => 19.3052,
                'longitud' => -99.2134,
                'servicios' => 'Urgencias, UCI, Cirugía, Pediatría',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital de Especialidades CMN Siglo XXI (IMSS)',
                'tipo' => 'IMSS',
                'nivel' => 'tercero',
                'direccion' => 'Av. Cuauhtémoc 330, Doctores, Cuauhtémoc, CDMX',
                'telefono' => '55 5627 6900',
                'latitud' => 19.4115,
                'longitud' => -99.1558,
                'servicios' => 'Urgencias, UCI, Cirugía, Cardiología, Oncología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Infantil de México Federico Gómez',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Dr. Márquez 162, Doctores, Cuauhtémoc, CDMX',
                'telefono' => '55 5228 9917',
                'latitud' => 19.4137,
                'longitud' => -99.1533,
                'servicios' => 'Urgencias pediátricas, UCI pediátrica, Cirugía pediátrica',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Central Militar',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Blvd. Manuel Ávila Camacho s/n, Lomas de Sotelo, CDMX',
                'telefono' => '55 5557 3400',
                'latitud' => 19.4423,
                'longitud' => -99.2171,
                'servicios' => 'Urgencias, UCI, Cirugía, Traumatología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital ABC Observatorio',
                'tipo' => 'privado',
                'nivel' => 'tercero',
                'direccion' => 'Av. Observatorio 395, Álvaro Obregón, CDMX',
                'telefono' => '55 5230 8000',
                'latitud' => 19.4042,
                'longitud' => -99.2109,
                'servicios' => 'Urgencias, UCI, Cirugía, Cardiología, Pediatría',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Militar de Especialidades de la Mujer',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Av. Ejército Nacional 1, Lomas de Sotelo, CDMX',
                'telefono' => '55 5557 3400',
                'latitud' => 19.4411,
                'longitud' => -99.2176,
                'servicios' => 'Ginecología, Obstetricia, Pediatría, Urgencias',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Nacional Homeopático',
                'tipo' => 'público',
                'nivel' => 'segundo',
                'direccion' => 'Calz. de Tlalpan 4363, Toriello Guerra, Tlalpan, CDMX',
                'telefono' => '55 5573 5100',
                'latitud' => 19.2949,
                'longitud' => -99.1498,
                'servicios' => 'Urgencias, Cirugía, Medicina General',
                'tiene_urgencias' => true,
                'tiene_uci' => false,
            ],
            [
                'nombre' => 'Hospital General Dr. Manuel Gea González',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Calz. de Tlalpan 4800, Sección XVI, Tlalpan, CDMX',
                'telefono' => '55 4000 3000',
                'latitud' => 19.2920,
                'longitud' => -99.1525,
                'servicios' => 'Urgencias, UCI, Cirugía, Dermatología, Oncología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Instituto Nacional de Ciencias Médicas y Nutrición Salvador Zubirán',
                'tipo' => 'público',
                'nivel' => 'tercero',
                'direccion' => 'Vasco de Quiroga 15, Belisario Domínguez, Tlalpan, CDMX',
                'telefono' => '55 5487 0900',
                'latitud' => 19.2853,
                'longitud' => -99.1511,
                'servicios' => 'Urgencias, UCI, Endocrinología, Gastroenterología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Ángeles Mocel',
                'tipo' => 'privado',
                'nivel' => 'segundo',
                'direccion' => 'Gral. Juan Cano 30, San Miguel Chapultepec, CDMX',
                'telefono' => '55 5516 0987',
                'latitud' => 19.4137,
                'longitud' => -99.1926,
                'servicios' => 'Urgencias, Cirugía, Ginecología',
                'tiene_urgencias' => true,
                'tiene_uci' => false,
            ],
            [
                'nombre' => 'Hospital San Ángel Inn Universidad',
                'tipo' => 'privado',
                'nivel' => 'tercero',
                'direccion' => 'Av. Universidad 1080, Del Valle, Benito Juárez, CDMX',
                'telefono' => '55 5488 0000',
                'latitud' => 19.3742,
                'longitud' => -99.1698,
                'servicios' => 'Urgencias, UCI, Cirugía, Cardiología',
                'tiene_urgencias' => true,
                'tiene_uci' => true,
            ],
            [
                'nombre' => 'Hospital Torreón del Sur',
                'tipo' => 'privado',
                'nivel' => 'segundo',
                'direccion' => 'Av. División del Norte 2777, Del Valle, CDMX',
                'telefono' => '55 5524 0100',
                'latitud' => 19.3732,
                'longitud' => -99.1601,
                'servicios' => 'Urgencias, Cirugía, Medicina General',
                'tiene_urgencias' => true,
                'tiene_uci' => false,
            ],
        ];

        foreach ($hospitales as $h) {
            Hospital::firstOrCreate(['nombre' => $h['nombre']], $h);
        }

        $this->command->info('✅ ' . count($hospitales) . ' hospitales creados.');
    }
}